import { PrismaClient } from "@prisma/client";

export async function seedPromotionalMaterials(prisma: PrismaClient) {
  console.log("📦 Seeding Promotional Materials...");

  const data = [
    // ----------------------------------------------------
    // Category: Premium_item
    // ----------------------------------------------------
    { sku: "PREM-001", name: "สมุดฉีก", category: "Premium_item", unit: "เล่ม", price: 25, quantity: 100 },
    { sku: "PREM-002", name: "ถุงผ้าสปันสีแดง \"โลโก้ปืนใหญ่\"", category: "Premium_item", unit: "ใบ", price: 35, quantity: 200 },
    { sku: "PREM-003", name: "เสื้อแขนยาว ปืนใหญ่ สีแดง", category: "Premium_item", unit: "ตัว", price: 250, quantity: 150 },
    { sku: "PREM-004", name: "เสื้อแขนยาว ปืนใหญ่ สีแดง 3XL", category: "Premium_item", unit: "ตัว", price: 270, quantity: 50 },
    { sku: "PREM-005", name: "หมวกคลุมหน้าสีแดง", category: "Premium_item", unit: "ใบ", price: 120, quantity: 100 },
    { sku: "PREM-006", name: "น้ำดื่มตราปืนใหญ่ แพคละ 24 ขวด", category: "Premium_item", unit: "แพค", price: 60, quantity: 80 },
    { sku: "PREM-007", name: "ถุงพลาสติกหูหิ้ว", category: "Premium_item", unit: "แพค", price: 45, quantity: 300 },
    { sku: "PREM-008", name: "แก้วแดง", category: "Premium_item", unit: "ใบ", price: 50, quantity: 150 },
    { sku: "PREM-009", name: "ที่เปิดขวดน้ำ", category: "Premium_item", unit: "อัน", price: 20, quantity: 250 },
    { sku: "PREM-010", name: "หมอนเทอรา-ซอร์บ เขียว", category: "Premium_item", unit: "ใบ", price: 180, quantity: 60 },
    { sku: "PREM-011", name: "หมอนเทอรา-ซอร์บ แดง", category: "Premium_item", unit: "ใบ", price: 180, quantity: 60 },
    { sku: "PREM-012", name: "ร่ม ตีกอล์ฟ 30 นิ้ว กัน UV", category: "Premium_item", unit: "คัน", price: 350, quantity: 40 },
    { sku: "PREM-013", name: "เสื้อลายสก๊อต", category: "Premium_item", unit: "ตัว", price: 280, quantity: 70 },
    { sku: "PREM-014", name: "น้ำยาล้างจาน ตราปืนใหญ่ บรรจุ 24 ซอง/ลัง", category: "Premium_item", unit: "ลัง", price: 240, quantity: 30 },
    { sku: "PREM-015", name: "สติ๊กเกอร์ปืนใหญ่ ขนาดใหญ่", category: "Premium_item", unit: "แผ่น", price: 15, quantity: 500 },
    { sku: "PREM-016", name: "ป้ายราคาพิเศษ", category: "Premium_item", unit: "แผ่น", price: 10, quantity: 300 },
    { sku: "PREM-017", name: "สติกเกอร์พรอมมิส", category: "Premium_item", unit: "แผ่น", price: 15, quantity: 400 },
    { sku: "PREM-018", name: "บัตรเชิญประชุมเกษตรกร", category: "Premium_item", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "PREM-019", name: "คูปองจับสลาก ตราปืนใหญ่", category: "Premium_item", unit: "ใบ", price: 2, quantity: 2000 },
    { sku: "PREM-020", name: "กล่องใสชุดฟ้าประธาน", category: "Premium_item", unit: "กล่อง", price: 150, quantity: 50 },
    { sku: "PREM-021", name: "ร่มชายหาด", category: "Premium_item", unit: "คัน", price: 550, quantity: 25 },

    // ----------------------------------------------------
    // Category: PP_Board
    // ----------------------------------------------------
    { sku: "PPB-001", name: "สติมเท็กซ์ โกลด์ (นาข้าว) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 100 },
    { sku: "PPB-002", name: "สติมเพล็กซ์(ทุเรียน) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 100 },
    { sku: "PPB-003", name: "ควีแลนท์ ไมเนอร์(ทุเรียน) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 100 },
    { sku: "PPB-004", name: "ควีแลนท์ ไมเนอร์(ชมพู่) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 80 },
    { sku: "PPB-005", name: "ควีแลนท์ ไมเนอร์(ลำไย) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 80 },
    { sku: "PPB-006", name: "ควีแลนท์ แคลเซียม ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 100 },
    { sku: "PPB-007", name: "เทอรา ซอร์บ ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 100 },
    { sku: "PPB-008", name: "เทอรา ซอร์บ เรดิคูรา ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 100 },
    { sku: "PPB-009", name: "สติมเพล็กซ์ แม็กซ์(นาข้าว) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 100 },
    { sku: "PPB-010", name: "สติมเพล็กซ์ แม็กซ์(ผัก) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 100 },
    { sku: "PPB-011", name: "ชุดฟื้นทรัพย์ ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 80 },
    { sku: "PPB-012", name: "ชุดเปิดทรัพย์ ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 80 },
    { sku: "PPB-013", name: "ชุดเสริมทรัพย์ ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 80 },
    { sku: "PPB-014", name: "ชุดออมทรัพย์ ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 80 },
    { sku: "PPB-015", name: "ชุดรับทรัพย์ ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 80 },
    { sku: "PPB-016", name: "แอพพรูพ 40 เอสซี ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-017", name: "แฮกทริก ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-018", name: "เทคนิค ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-019", name: "เพอฟอร์ม ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-020", name: "เพอฟอร์ม(ทุเรียน) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-021", name: "เพอฟอร์ม(ข้าวโพด) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-022", name: "พรอมมิส(ข้าว) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-023", name: "โนม็อบ ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-024", name: "พรอมมิส(นาข้าว) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-025", name: "พรอมมิส(ข้าวโพด) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-026", name: "พรอมมิส(ทุเรียน) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-027", name: "พรอมมิส(ไม้ผล) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-028", name: "โรดแม็บ ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-029", name: "ไรเบน ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-030", name: "ไตรโซดริน ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-031", name: "ไตรโซดริน(หนอนกอข้าว) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-032", name: "ดิสแทนท์(ข้าว) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-033", name: "ดิสแทนท์(ทุเรียน) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-034", name: "ดิสแทนท์+เพอฟอร์ม(ข้าว) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-035", name: "ดิสแทนท์+เพอฟอร์ม(ข้าวโพด) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-036", name: "ดิสแทนท์+เพอฟอร์ม(ทุเรียน) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-037", name: "ดิสแทนท์+โรดแม็บ(ข้าว) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-038", name: "ดิสแทนท์+โรดแม็บ(ทุเรียน) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-039", name: "เฟียร์ส ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-040", name: "แฮพเพ่น ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-041", name: "พังเจอร์ ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-042", name: "เรดแน็พ ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-043", name: "อะเวค ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-044", name: "แฮตแทค ขนาด 40x60 ซม.", category: "PP_Board", unit: "แผ่น", price: 90, quantity: 100 },
    { sku: "PPB-045", name: "แฮตแทค ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 100 },
    { sku: "PPB-046", name: "บีเฟซ ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-047", name: "ซิกแนล ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-048", name: "จัสคอล70 ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-049", name: "โคชชิ่ง ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-050", name: "คิวบีน ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-051", name: "เอแลค ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-052", name: "เฟสทีพ ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-053", name: "ซัมมิท ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-054", name: "ซัมมิท+จัสคอล70 ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-055", name: "เซจคิว ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-056", name: "เอ็กไซท์ 48 + พาเหรด 84 ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-057", name: "เอ็กไซท์ 48 ขาว ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-058", name: "เอ็กไซท์ 48 แดง ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-059", name: "คีพเปอร์ ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-060", name: "ไซบลาส ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-061", name: "พาร์25 ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-062", name: "ซีโตเร่ ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-063", name: "เอมัส ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-064", name: "บล็อกกิ้ง ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-065", name: "ซูโด ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-066", name: "คาบัน ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 90 },
    { sku: "PPB-067", name: "ออเดรย์(นาข้าว) ขนาด 40x60 ซม.", category: "PP_Board", unit: "แผ่น", price: 90, quantity: 90 },
    { sku: "PPB-068", name: "ออเดรย์(ทุเรียน) ขนาด 40x60 ซม.", category: "PP_Board", unit: "แผ่น", price: 90, quantity: 90 },
    { sku: "PPB-069", name: "แลคเกอร์-พาวเวอร์ ขนาด 40x60 ซม.", category: "PP_Board", unit: "แผ่น", price: 90, quantity: 90 },
    { sku: "PPB-070", name: "โลโก้ปืนใหญ่ ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 150 },
    { sku: "PPB-071", name: "มะม่วง ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 80 },
    { sku: "PPB-072", name: "ชมพู่ ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 80 },
    { sku: "PPB-073", name: "มังคุด ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 80 },
    { sku: "PPB-074", name: "ลำไย ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 80 },
    { sku: "PPB-075", name: "ผลิตภัณฑ์ตราปืนใหญ่เพื่อชาวไร่อ้อย ขนาด 80x110 ซม.", category: "PP_Board", unit: "แผ่น", price: 180, quantity: 70 },
    { sku: "PPB-076", name: "แตงโม ขนาด 80x110 ซม.", category: "PP_Board", unit: "แผ่น", price: 180, quantity: 70 },
    { sku: "PPB-077", name: "อลูฟอส(กระชาย) ขนาด 40x60 ซม.", category: "PP_Board", unit: "แผ่น", price: 90, quantity: 80 },
    { sku: "PPB-078", name: "บีทเทิล ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 80 },
    { sku: "PPB-079", name: "กลูโฟซิเนต + แอมโมเนีย ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 80 },
    { sku: "PPB-081", name: "เทคเคน ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 80 },
    { sku: "PPB-082", name: "แฮตแทค + ไซโนอีส ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 80 },
    { sku: "PPB-083", name: "คร็อพโทนิค (นาข้าว) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 80 },
    { sku: "PPB-084", name: "คร็อพโทนิค (ทุเรียน) ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 80 },
    { sku: "PPB-085", name: "อัลเทอร่า-เค ขนาด 60x80 ซม.", category: "PP_Board", unit: "แผ่น", price: 120, quantity: 80 },

    // ----------------------------------------------------
    // Category: Banner
    // ----------------------------------------------------
    { sku: "BNR-001", name: "อลูฟอส ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-002", name: "ควีแลนท์ ซิงค์แมงกานีส ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-003", name: "ควีแลนท์ ไมเนอร์ ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-004", name: "เทอรา-ซอร์บ เรดิคูรา ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-005", name: "เทคนิค ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-006", name: "เพอฟอร์ม(ข้าวโพด) ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-007", name: "ดิสแทนท์(ข้าว) ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-008", name: "ดิสแทนท์(ทุเรียน) ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-009", name: "ดิสแทนท์+เพอฟอร์ม(ข้าวโพด) ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-010", name: "ดิสแทนท์+เพอฟอร์ม(ข้าว) ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-011", name: "ดิสแทนท์+เพอฟอร์ม(ทุเรียน) ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-012", name: "ดิสแทนท์+โรดแม็บ(ข้าว) ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-013", name: "แฮพเพ่น ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-014", name: "เฟียร์ส ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-015", name: "แฮตแทค ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-016", name: "ซิกแนล ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-017", name: "บีเฟซ ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-018", name: "โคชชิ่ง ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-019", name: "อัคคาบัน ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-020", name: "บล็อกกิ้ง ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-021", name: "ซูโด ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-022", name: "โลโก้ปืนใหญ่ ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 100 },
    { sku: "BNR-023", name: "อัลเทอร่า ซีรีส์ 7 สูตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-024", name: "มังคุด ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-025", name: "เทคเคน ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-026", name: "เทอรา ซอร์บ ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-027", name: "แอพพรูพ 40 เอสซี ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-028", name: "เพอฟอร์ม ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-029", name: "โรดแม็บ ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-030", name: "เรดแน็พ ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-031", name: "ซีโตเร่ ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-032", name: "บิทเทิล ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-033", name: "ไซบลาส ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-034", name: "อะเวค ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-035", name: "สติมเท็กซ์ โกลด์(ผลไม้) ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-036", name: "คีพเปอร์ ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-037", name: "สติมเท็กซ์ โกลด์(นาข้าว) ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },
    { sku: "BNR-038", name: "คร็อพโทนิค (นาข้าว) ขนาด 60x80 ซม.", category: "Banner", unit: "ผืน", price: 150, quantity: 50 },
    { sku: "BNR-039", name: "คร็อพโทนิค (ทุเรียน) ขนาด 60x80 ซม.", category: "Banner", unit: "ผืน", price: 150, quantity: 50 },
    { sku: "BNR-040", name: "อัลเทอร่า - เค ขนาด 1x2 เมตร", category: "Banner", unit: "ผืน", price: 250, quantity: 50 },

    // ----------------------------------------------------
    // Category: Leaflet
    // ----------------------------------------------------
    { sku: "LFL-001", name: "เล่มคู่มือทุเรียน", category: "Leaflet", unit: "เล่ม", price: 45, quantity: 500 },
    { sku: "LFL-002", name: "เล่มคู่มือนาข้าว", category: "Leaflet", unit: "เล่ม", price: 45, quantity: 500 },
    { sku: "LFL-003", name: "ใบปลิวคู่มือนาข้าวสำหรับการใช้โดรน", category: "Leaflet", unit: "ใบ", price: 8, quantity: 1000 },
    { sku: "LFL-004", name: "ใบปลิวมะม่วง", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-005", name: "ใบปลิวเงาะ", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-006", name: "ใบปลิวลำไย", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-007", name: "ใบปลิวชมพู่", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-008", name: "ใบปลิวมังคุด", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-009", name: "ใบปลิวมะนาว", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-010", name: "ใบปลิวหอม", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-011", name: "ใบปลิวพริก", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-012", name: "ใบปลิวผลิตภัณฑ์ตราปืนใหญ่เพื่อชาวไร่อ้อย", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-013", name: "ใบปลิวมันสำปะหลัง", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-014", name: "ใบปลิวผักกินใบ", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-015", name: "ใบปลิวกล้วยไม้", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-016", name: "ใบปลิวเทอรา ซอร์บ", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-017", name: "ใบปลิวเทอรา-ซอร์บ เรดิคูรา", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-018", name: "ใบปลิวควีแลนท์ แคลเซียม", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-019", name: "ใบปลิวเพอฟอร์ม", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-020", name: "ใบปลิวเพอฟอร์+ดิสแทนท์ (ข้าวโพด)", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-021", name: "ใบปลิวคีพเปอร์", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-022", name: "ใบปลิวซิกแนล", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-023", name: "ใบปลิวเอมัส", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-024", name: "ใบปลิวแท็คทีมพรี", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-025", name: "ใบปลิวซัมมิท+จัสคอล70", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-026", name: "ใบปลิวแฮตแทค", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-027", name: "ใบปลิวแลคเกอร์-พาวเวอร์", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-028", name: "ใบปลิวซูโด+บล็อกกิ้ง+อัคคาบัน", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-029", name: "ใบปลิวเรดแน็พ+เฟียร์ส+แฮพเพ่น", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },
    { sku: "LFL-030", name: "ใบปลิวสติมเท็กซ์ โกลด์", category: "Leaflet", unit: "ใบ", price: 5, quantity: 1000 },

    // ----------------------------------------------------
    // Category: อุปกรณ์จัดงาน
    // ----------------------------------------------------
    { sku: "EQP-001", name: "เต็นท์", category: "อุปกรณ์จัดงาน", unit: "หลัง", price: 2500, quantity: 10 },
    { sku: "EQP-002", name: "โต๊ะใหญ่ พร้อมผ้าปู", category: "อุปกรณ์จัดงาน", unit: "ชุด", price: 600, quantity: 20 },
    { sku: "EQP-003", name: "โต๊ะเล็ก พร้อมผ้าปู", category: "อุปกรณ์จัดงาน", unit: "ชุด", price: 400, quantity: 30 },
    { sku: "EQP-004", name: "ธงชายหาดใหญ่", category: "อุปกรณ์จัดงาน", unit: "ชุด", price: 1200, quantity: 15 },
    { sku: "EQP-005", name: "ธงชายหาดเล็ก", category: "อุปกรณ์จัดงาน", unit: "ชุด", price: 850, quantity: 20 },
    { sku: "EQP-006", name: "Backdrop ใหญ่", category: "อุปกรณ์จัดงาน", unit: "ชุด", price: 4500, quantity: 5 },
    { sku: "EQP-007", name: "Backdrop เล็ก", category: "อุปกรณ์จัดงาน", unit: "ชุด", price: 2800, quantity: 8 },
    { sku: "EQP-008", name: "ชุดอุปกรณ์ผสมยา", category: "อุปกรณ์จัดงาน", unit: "ชุด", price: 1500, quantity: 15 },
    { sku: "EQP-009", name: "ลำโพง JBL พร้อมไมค์", category: "อุปกรณ์จัดงาน", unit: "ชุด", price: 8500, quantity: 4 },
    { sku: "EQP-010", name: "ขวดสินค้าตัวอย่าง ระบุ...", category: "อุปกรณ์จัดงาน", unit: "ชุด", price: 300, quantity: 50 },
    { sku: "EQP-011", name: "ธงราว", category: "อุปกรณ์จัดงาน", unit: "เส้น", price: 200, quantity: 40 },
    { sku: "EQP-012", name: "ชุดเกมส์โยนห่วง", category: "อุปกรณ์จัดงาน", unit: "ชุด", price: 750, quantity: 10 },
    { sku: "EQP-013", name: "ชุดเกมส์ปาเป้า", category: "อุปกรณ์จัดงาน", unit: "ชุด", price: 800, quantity: 10 },
    { sku: "EQP-014", name: "แท่นหมุนวงล้อ", category: "อุปกรณ์จัดงาน", unit: "ชุด", price: 1800, quantity: 6 },
    { sku: "EQP-015", name: "ชุดเกมส์สอยดาว", category: "อุปกรณ์จัดงาน", unit: "ชุด", price: 1200, quantity: 8 },
    { sku: "EQP-016", name: "PVC รายการพิเศษ ระบุ...", category: "อุปกรณ์จัดงาน", unit: "แผ่น", price: 500, quantity: 30 },
    { sku: "EQP-017", name: "กล่องจับรางวัล ขนาดเล็ก", category: "อุปกรณ์จัดงาน", unit: "กล่อง", price: 350, quantity: 15 },
    { sku: "EQP-018", name: "กล่องจับรางวัล ขนาดกลาง", category: "อุปกรณ์จัดงาน", unit: "กล่อง", price: 550, quantity: 10 },
    { sku: "EQP-019", name: "ตู้หมุนสลากรางวัล", category: "อุปกรณ์จัดงาน", unit: "ตู้", price: 2200, quantity: 4 },
    { sku: "EQP-020", name: "Standy รายการพิเศษ ระบุ ....", category: "อุปกรณ์จัดงาน", unit: "ชุด", price: 650, quantity: 20 },
    { sku: "EQP-021", name: "ร่มสนาม", category: "อุปกรณ์จัดงาน", unit: "คัน", price: 1400, quantity: 12 },
    { sku: "EQP-022", name: "หญ้าเทียม", category: "อุปกรณ์จัดงาน", unit: "ม้วน", price: 1800, quantity: 8 },
  ];

  for (const item of data) {
    await prisma.promotionalMaterial.upsert({
      where: { sku: item.sku },
      update: {
        name: item.name,
        category: item.category,
        unit: item.unit,
        price: item.price,
        quantity: item.quantity,
        status: "ACTIVE",
      },
      create: {
        sku: item.sku,
        name: item.name,
        category: item.category,
        unit: item.unit,
        price: item.price,
        quantity: item.quantity,
        status: "ACTIVE",
      },
    });
  }

  console.log(`✅ Seeded ${data.length} Promotional Materials.`);
}
