import { PrismaClient, Prisma, ActivityStatus, ActivityHelperStatus, ActivityApprovalAction, ActivityApprovalStep, ActivityResultStatus, AttachmentCategory, DemoPlotStatus } from "@prisma/client";
import { SeedContext, upsertSeedPlan } from "./seed-helpers";

export async function seedType7(prisma: PrismaClient, ctx: SeedContext) {
  const store0 = ctx.customers[0];
  const prod0 = ctx.products[0];
  const prod1 = ctx.products[1] || ctx.products[0];
  const helper0 = ctx.helperEmployees[0];

  // 1. Create/Upsert DemoPlots
  const demoPlot1 = await prisma.demoPlot.upsert({
    where: { code: "DP2608S001" },
    update: {
      name: "แปลงสาธิตทุเรียนหมอนทอง สวนนายสมชาย",
      ownerName: "นายสมชาย ใจดี",
      customerId: store0.id,
      employeeId: ctx.primaryEmployee.id,
      cropCategory: "พืชสวน",
      cropName: "ทุเรียน",
      areaRai: new Prisma.Decimal(5.0),
      treeCount: 100,
      location: "ต.ท่าใหม่ อ.ท่าใหม่ จ.จันทบุรี",
      province: "จันทบุรี",
      district: "ท่าใหม่",
      primaryProductId: prod0.id,
      primaryProductName: prod0.name,
      objective: "ทดสอบการส่งเสริมการแตกใบอ่อนและการสะสมอาหารก่อนออกดอก",
      experimentDetail: "พ่นอัตรา 20 ซีซี ต่อน้ำ 20 ลิตร ทุก 7 วัน รวม 3 ครั้ง",
      startDate: new Date("2026-08-01T00:00:00.000Z"),
      plantingDate: new Date("2026-08-01T00:00:00.000Z"),
      plantingAreaCondition: "ดินร่วนปนทราย ระบบน้ำมินิสปริงเกลอร์",
      usageMethod: "ฉีดพ่นทางใบช่วงเช้า",
      status: DemoPlotStatus.IN_PROGRESS,
    },
    create: {
      code: "DP2608S001",
      name: "แปลงสาธิตทุเรียนหมอนทอง สวนนายสมชาย",
      ownerName: "นายสมชาย ใจดี",
      customerId: store0.id,
      employeeId: ctx.primaryEmployee.id,
      cropCategory: "พืชสวน",
      cropName: "ทุเรียน",
      areaRai: new Prisma.Decimal(5.0),
      treeCount: 100,
      location: "ต.ท่าใหม่ อ.ท่าใหม่ จ.จันทบุรี",
      province: "จันทบุรี",
      district: "ท่าใหม่",
      primaryProductId: prod0.id,
      primaryProductName: prod0.name,
      objective: "ทดสอบการส่งเสริมการแตกใบอ่อนและการสะสมอาหารก่อนออกดอก",
      experimentDetail: "พ่นอัตรา 20 ซีซี ต่อน้ำ 20 ลิตร ทุก 7 วัน รวม 3 ครั้ง",
      startDate: new Date("2026-08-01T00:00:00.000Z"),
      plantingDate: new Date("2026-08-01T00:00:00.000Z"),
      plantingAreaCondition: "ดินร่วนปนทราย ระบบน้ำมินิสปริงเกลอร์",
      usageMethod: "ฉีดพ่นทางใบช่วงเช้า",
      status: DemoPlotStatus.IN_PROGRESS,
    },
  });

  const demoPlot2 = await prisma.demoPlot.upsert({
    where: { code: "DP2608S002" },
    update: {
      name: "แปลงสาธิตข้าวหอมมะลิ สวนนายวีระ",
      ownerName: "นายวีระ ชูใจ",
      customerId: store0.id,
      employeeId: ctx.primaryEmployee.id,
      cropCategory: "พืชไร่",
      cropName: "ข้าว",
      areaRai: new Prisma.Decimal(10.0),
      location: "ต.เดิมบาง อ.เดิมบางนางบวช จ.สุพรรณบุรี",
      province: "สุพรรณบุรี",
      district: "เดิมบางนางบวช",
      primaryProductId: prod1.id,
      primaryProductName: prod1.name,
      objective: "ทดสอบการเพิ่มผลผลิตและลดอัตราเมล็ดลีบ",
      experimentDetail: "พ่นช่วงข้าวตั้งท้องและออกรวง 50%",
      startDate: new Date("2026-07-15T00:00:00.000Z"),
      closedDate: new Date("2026-08-20T00:00:00.000Z"),
      finalHarvestDate: new Date("2026-08-20T00:00:00.000Z"),
      controlYieldKg: new Prisma.Decimal(520.0),
      demoYieldKg: new Prisma.Decimal(650.0),
      yieldIncreasePercent: new Prisma.Decimal(25.0),
      farmerSatisfaction: 5,
      commercialPotential: "เกษตรกรสั่งซื้อใช้ทั้งแปลง 50 ไร่ในฤดูถัดไป",
      finalSummaryNotes: "ผลผลิตเพิ่มขึ้น 25% เมล็ดเต่งใส น้ำหนักดี",
      status: DemoPlotStatus.COMPLETED,
    },
    create: {
      code: "DP2608S002",
      name: "แปลงสาธิตข้าวหอมมะลิ สวนนายวีระ",
      ownerName: "นายวีระ ชูใจ",
      customerId: store0.id,
      employeeId: ctx.primaryEmployee.id,
      cropCategory: "พืชไร่",
      cropName: "ข้าว",
      areaRai: new Prisma.Decimal(10.0),
      location: "ต.เดิมบาง อ.เดิมบางนางบวช จ.สุพรรณบุรี",
      province: "สุพรรณบุรี",
      district: "เดิมบางนางบวช",
      primaryProductId: prod1.id,
      primaryProductName: prod1.name,
      objective: "ทดสอบการเพิ่มผลผลิตและลดอัตราเมล็ดลีบ",
      experimentDetail: "พ่นช่วงข้าวตั้งท้องและออกรวง 50%",
      startDate: new Date("2026-07-15T00:00:00.000Z"),
      closedDate: new Date("2026-08-20T00:00:00.000Z"),
      finalHarvestDate: new Date("2026-08-20T00:00:00.000Z"),
      controlYieldKg: new Prisma.Decimal(520.0),
      demoYieldKg: new Prisma.Decimal(650.0),
      yieldIncreasePercent: new Prisma.Decimal(25.0),
      farmerSatisfaction: 5,
      commercialPotential: "เกษตรกรสั่งซื้อใช้ทั้งแปลง 50 ไร่ในฤดูถัดไป",
      finalSummaryNotes: "ผลผลิตเพิ่มขึ้น 25% เมล็ดเต่งใส น้ำหนักดี",
      status: DemoPlotStatus.COMPLETED,
    },
  });

  // Plan 1: Demo Plot Creation + APPROVED + Actual + DemoPlotVisit
  const plan1Res = await upsertSeedPlan(prisma, {
    code: "TP2608S071",
    title: "ทำแปลงสาธิตบำรุงทุเรียนหมอนทอง จันทบุรี",
    primaryWorkTypeCode: "TYPE_7",
    startDate: new Date("2026-08-11T09:00:00.000Z"),
    endDate: new Date("2026-08-11T17:00:00.000Z"),
    province: "จันทบุรี",
    district: "ท่าใหม่",
    location: "สวนทุเรียนนายสมชาย อ.ท่าใหม่ จ.จันทบุรี",
    objective: "เริ่มต้นทำแปลงสาธิตและเก็บข้อมูลแปลงรอบที่ 1",
    status: ActivityStatus.APPROVED,
    employeeId: ctx.primaryEmployee.id,
    createdById: ctx.adminUser.id,
    currentApproverEmployeeId: ctx.managerEmployee.id,
    submittedAt: new Date("2026-08-03T09:00:00.000Z"),
    approvedAt: new Date("2026-08-04T10:00:00.000Z"),
    stores: [
      { workTypeCode: "TYPE_7", storeId: store0.id, storeName: store0.name },
    ],
    products: [
      { workTypeCode: "TYPE_7", storeId: store0.id, productId: prod0.id, productName: prod0.name },
    ],
    helpers: [
      { employeeId: helper0.id, departmentId: helper0.departmentId, departmentName: helper0.departmentName, status: ActivityHelperStatus.APPROVED, approvedById: ctx.managerEmployee.id, approvedAt: new Date("2026-08-04T09:00:00.000Z") },
    ],
    items: [
      {
        workTypeCode: "TYPE_7",
        customerName: store0.name,
        plotActivityType: "CREATE",
        plotOwnerName: "นายสมชาย ใจดี",
        plotProductName: prod0.name,
        plotCropCategory: "พืชสวน",
        plotCropName: "ทุเรียน",
        plotAreaRai: 5.0,
        plotTreeCount: 100,
        plotCount: 1,
        existingPlotId: demoPlot1.id,
        plotGrowthStage: "แตกใบอ่อน",
        plotStatus: "IN_PROGRESS",
        detail: "ฉีดพ่นรอบที่ 1 และติดป้ายแปลงสาธิต",
      },
    ],
    approvalLogs: [
      { userId: ctx.adminUser.id, action: ActivityApprovalAction.SUBMIT, step: ActivityApprovalStep.LINE_APPROVAL, fromStatus: ActivityStatus.DRAFT, toStatus: ActivityStatus.PENDING_LINE_APPROVAL, createdAt: new Date("2026-08-03T09:00:00.000Z") },
      { userId: ctx.adminUser.id, action: ActivityApprovalAction.APPROVE, step: ActivityApprovalStep.LINE_APPROVAL, fromStatus: ActivityStatus.PENDING_LINE_APPROVAL, toStatus: ActivityStatus.APPROVED, createdAt: new Date("2026-08-04T10:00:00.000Z") },
    ],
    actualResult: {
      actualStartDate: new Date("2026-08-11T09:00:00.000Z"),
      actualEndDate: new Date("2026-08-11T16:00:00.000Z"),
      actualAttendeesCount: 3,
      resultStatus: ActivityResultStatus.COMPLETED,
      resultSummary: "พ่นสารบำรุงรอบที่ 1 เรียบร้อย ติดตั้งป้ายแปลงสาธิตและเก็บภาพสภาพแปลงก่อนฉีดพ่น",
      demoPlotsCreated: 1,
      demoPlotsFollowedUp: 0,
      discussionResult: "เกษตรกรให้ความร่วมมือดีมาก และบันทึกตารางการให้น้ำสม่ำเสมอ",
      recordedById: ctx.adminUser.id,
      demoResults: [
        {
          demoPlotId: demoPlot1.id,
          cropAgeValue: "45",
          cropAgeUnit: "วันหลังตัดแต่ง",
          growthStage: "ระยะใบเพสลาด",
          cropCondition: "สมบูรณ์ดี ใบเขียวเข้ม",
          productResponse: "ตอบสนองดี ยอดเดินสม่ำเสมอ",
          satisfactionScore: 5,
        },
      ],
      attachments: [
        { workTypeCode: "TYPE_7", storeId: store0.id, productId: prod0.id, category: AttachmentCategory.PLOT, fileUrl: "/uploads/activity-plans-seed/plot-overview-1.svg", fileName: "demo-plot-overview.svg" },
        { workTypeCode: "TYPE_7", storeId: store0.id, productId: prod0.id, category: AttachmentCategory.CROP, fileUrl: "/uploads/activity-plans-seed/crop-sample-1.svg", fileName: "demo-durian-leaves.svg" },
      ],
    },
  });

  // Sync DemoPlotVisit for Plan 1
  await prisma.demoPlotVisit.deleteMany({ where: { activityPlanId: plan1Res.planId } });
  await prisma.demoPlotVisit.create({
    data: {
      demoPlotId: demoPlot1.id,
      activityPlanId: plan1Res.planId,
      visitNumber: 1,
      visitDate: new Date("2026-08-11T09:00:00.000Z"),
      daysSinceStart: 10,
      cropAgeValue: 45,
      cropAgeUnit: "วัน",
      growthStage: "ระยะใบเพสลาด",
      cropCondition: "สมบูรณ์ดี",
      productResponse: "พืชตอบสนองดี",
      usageMethod: "ฉีดพ่นทางใบอัตรา 20 ซีซี/น้ำ 20 ลิตร",
      productUsedQty: 2,
      productUnitPrice: new Prisma.Decimal(385),
      productCost: new Prisma.Decimal(770),
      cropImageUrls: ["/uploads/activity-plans-seed/crop-sample-1.svg"],
      plotImageUrls: ["/uploads/activity-plans-seed/plot-overview-1.svg"],
      notes: "ตรวจรอบแรกหลังเริ่มทำแปลงสาธิต 10 วัน",
    },
  });

  // Plan 2: Demo Plot Follow Up + Evaluation + APPROVED + Actual
  const plan2Res = await upsertSeedPlan(prisma, {
    code: "TP2608S072",
    title: "ตรวจประเมินผลผลิตและปิดแปลงสาธิตข้าว สุพรรณบุรี",
    primaryWorkTypeCode: "TYPE_7",
    startDate: new Date("2026-08-20T09:00:00.000Z"),
    endDate: new Date("2026-08-20T17:00:00.000Z"),
    province: "สุพรรณบุรี",
    district: "เดิมบางนางบวช",
    location: "แปลงนาข้าวนายวีระ อ.เดิมบางนางบวช จ.สุพรรณบุรี",
    objective: "ชั่งน้ำหนักผลผลิตเปรียบเทียบแปลงควบคุมและปิดแปลงสาธิต",
    status: ActivityStatus.APPROVED,
    employeeId: ctx.primaryEmployee.id,
    createdById: ctx.adminUser.id,
    currentApproverEmployeeId: ctx.managerEmployee.id,
    submittedAt: new Date("2026-08-12T09:00:00.000Z"),
    approvedAt: new Date("2026-08-13T11:00:00.000Z"),
    stores: [
      { workTypeCode: "TYPE_7", storeId: store0.id, storeName: store0.name },
    ],
    products: [
      { workTypeCode: "TYPE_7", storeId: store0.id, productId: prod1.id, productName: prod1.name },
    ],
    items: [
      {
        workTypeCode: "TYPE_7",
        customerName: store0.name,
        plotActivityType: "FOLLOW_UP",
        plotOwnerName: "นายวีระ ชูใจ",
        plotProductName: prod1.name,
        plotCropCategory: "พืชไร่",
        plotCropName: "ข้าว",
        plotAreaRai: 10.0,
        existingPlotId: demoPlot2.id,
        plotGrowthStage: "เก็บเกี่ยว",
        plotStatus: "COMPLETED",
        detail: "ชั่งผลผลิตสุ่ม 1 ตารางเมตร 5 จุด",
      },
    ],
    approvalLogs: [
      { userId: ctx.adminUser.id, action: ActivityApprovalAction.SUBMIT, step: ActivityApprovalStep.LINE_APPROVAL, fromStatus: ActivityStatus.DRAFT, toStatus: ActivityStatus.PENDING_LINE_APPROVAL, createdAt: new Date("2026-08-12T09:00:00.000Z") },
      { userId: ctx.adminUser.id, action: ActivityApprovalAction.APPROVE, step: ActivityApprovalStep.LINE_APPROVAL, fromStatus: ActivityStatus.PENDING_LINE_APPROVAL, toStatus: ActivityStatus.APPROVED, createdAt: new Date("2026-08-13T11:00:00.000Z") },
    ],
    actualResult: {
      actualStartDate: new Date("2026-08-20T09:00:00.000Z"),
      actualEndDate: new Date("2026-08-20T16:00:00.000Z"),
      actualAttendeesCount: 4,
      resultStatus: ActivityResultStatus.COMPLETED,
      resultSummary: "ผลผลิตเฉลี่ยแปลงสาธิต 650 กก./ไร่ แปลงควบคุม 520 กก./ไร่ เพิ่มขึ้น 25%",
      demoPlotsCreated: 0,
      demoPlotsFollowedUp: 1,
      farmersCount: 4,
      recordedById: ctx.adminUser.id,
      demoResults: [
        {
          demoPlotId: demoPlot2.id,
          cropAgeValue: "110",
          cropAgeUnit: "วัน",
          growthStage: "เก็บเกี่ยวผลผลิต",
          cropCondition: "เมล็ดเต่งเต็มรวง ไม่ลีบ",
          productResponse: "เพิ่มน้ำหนักและความสมบูรณ์ชัดเจน",
          finalYieldKg: 650,
          controlYieldKg: 520,
          satisfactionScore: 5,
        },
      ],
      attachments: [
        { workTypeCode: "TYPE_7", storeId: store0.id, productId: prod1.id, category: AttachmentCategory.CROP, fileUrl: "/uploads/activity-plans-seed/crop-sample-1.svg", fileName: "demo-rice-harvest.svg" },
      ],
    },
  });

  // Sync DemoPlotVisit for Plan 2
  await prisma.demoPlotVisit.deleteMany({ where: { activityPlanId: plan2Res.planId } });
  await prisma.demoPlotVisit.create({
    data: {
      demoPlotId: demoPlot2.id,
      activityPlanId: plan2Res.planId,
      visitNumber: 3,
      visitDate: new Date("2026-08-20T09:00:00.000Z"),
      daysSinceStart: 35,
      cropAgeValue: 110,
      cropAgeUnit: "วัน",
      growthStage: "เก็บเกี่ยว",
      cropCondition: "สมบูรณ์ดีมาก",
      productResponse: "ผลผลิตเพิ่มขึ้น 25%",
      usageMethod: "เก็บเกี่ยวและชั่งน้ำหนักผลผลิต",
      productUsedQty: 0,
      cropImageUrls: ["/uploads/activity-plans-seed/crop-sample-1.svg"],
      notes: "เก็บเกี่ยวและสรุปผลสำเร็จของแปลงสาธิต",
    },
  });

  // Plan 3: PENDING_LINE_APPROVAL
  await upsertSeedPlan(prisma, {
    code: "TP2608S073",
    title: "แผนทำแปลงสาธิตข้าวโพดหวาน นครราชสีมา",
    primaryWorkTypeCode: "TYPE_7",
    startDate: new Date("2026-08-29T09:00:00.000Z"),
    endDate: new Date("2026-08-29T17:00:00.000Z"),
    province: "นครราชสีมา",
    district: "ปากช่อง",
    location: "แปลงเกษตรกร อ.ปากช่อง จ.นครราชสีมา",
    objective: "เตรียมทำแปลงสาธิตกำจัดหนอนกระทู้ข้าวโพดลายจุด",
    status: ActivityStatus.PENDING_LINE_APPROVAL,
    employeeId: ctx.primaryEmployee.id,
    createdById: ctx.adminUser.id,
    currentApproverEmployeeId: ctx.managerEmployee.id,
    submittedAt: new Date("2026-08-22T09:00:00.000Z"),
    stores: [
      { workTypeCode: "TYPE_7", storeId: store0.id, storeName: store0.name },
    ],
    items: [
      {
        workTypeCode: "TYPE_7",
        customerName: store0.name,
        plotActivityType: "CREATE",
        plotOwnerName: "นายประเสริฐ สุขใจ",
        plotProductName: prod0.name,
        plotCropCategory: "พืชไร่",
        plotCropName: "ข้าวโพด",
        plotAreaRai: 8.0,
        detail: "วางแปลงสาธิต 2 ซ้ำ",
      },
    ],
    approvalLogs: [
      { userId: ctx.adminUser.id, action: ActivityApprovalAction.SUBMIT, step: ActivityApprovalStep.LINE_APPROVAL, fromStatus: ActivityStatus.DRAFT, toStatus: ActivityStatus.PENDING_LINE_APPROVAL, createdAt: new Date("2026-08-22T09:00:00.000Z") },
    ],
  });
}
