export interface TripPlanMock {
  id: string;
  activityDate: string;
  responsible: string;
  approver: string;
  jobType: string;
  activityName: string;
  province: string;
  district: string;
  subdistrict: string;
  locationName: string;
  targetType: string;
  targetGoal: string;
  recordFields: string[];
  budgetType: string;
  budget: number;
  status: "PENDING" | "APPROVED" | "REJECTED" | "CANCELLED" | "FINISHED";
  // Activity Report Fields
  actualParticipants: number;
  actualNewCustomers: number;
  actualOrders: number;
  actualSales: number;
  targetParticipants: number;
  targetSales: number;
  performanceResult: string;
  plantType: string;
  plotsCount: number;
  growthStage: string;
  problemsFound: string;
  // Budget Report Fields
  actualBudget: number;
  otherExpenses: number;
}

export const targetTypeConfigs: Record<
  string,
  { goal: string; recordFields: string[] }
> = {
  "ติดตามลูกค้า": {
    goal: "1.จำนวนลูกค้าที่ต้องติดตาม (ราย)",
    recordFields: [
      "1. ลูกค้าที่เข้าพบ",
      "2. สินค้าที่เคยซื้อ",
      "3. ผลการติดตาม",
      "4. ปัญหาที่พบ",
      "5. สิ่งที่ต้องดำเนินการต่อ",
      "6. วันที่นัดหมายครั้งถัดไป",
    ],
  },
  "สร้างความสัมพันธ์": {
    goal: "1.จำนวนลูกค้าที่ต้องเข้าพบ (ราย)",
    recordFields: [
      "1. ลูกค้าที่เข้าพบ",
      "2. ประเด็นที่พูดคุย",
      "3. ความคิดเห็นของลูกค้า",
      "4. ความพึงพอใจของลูกค้า",
      "5. โอกาสทางธุรกิจที่พบ",
    ],
  },
  "รับทราบปัญหา": {
    goal: "1.จำนวนเคสที่ต้องติดตาม",
    recordFields: [
      "1. ลูกค้าที่แจ้งปัญหา",
      "2. ประเภทปัญหา",
      "   - สินค้าชำรุด",
      "   - ขอเคลมสินค้า",
      "   - การใช้งานสินค้า",
      "   - โรคและแมลง",
      "   - ส่งสินค้าไม่ครบ",
      "   - อื่น ๆ (ระบุ)",
      "3. พื้นที่เพาะปลูก",
      "4. รายละเอียดปัญหา",
      "5. รูปภาพประกอบ",
      "6. แนวทางแก้ไขเบื้องต้น",
    ],
  },
  "ให้คำปรึกษาทางการเกษตร  / ดีลเลอร์ / ซับดีลเลอร์": {
    goal: "1.จำนวนคนที่คาดว่าจะให้คำปรึกษา",
    recordFields: [
      "1. หัวข้อที่ให้คำแนะนำ",
      "2. ปัญหาของลูกค้า",
      "3. คำแนะนำที่ให้",
    ],
  },
  "แนะนำสินค้า": {
    goal: "1.จำนวนลูกค้าที่คาดว่าจะสนใจ",
    recordFields: [
      "1. สินค้าที่แนะนำ",
      "2. เหตุผลที่แนะนำ",
      "3. ความสนใจของลูกค้า",
      "4. ความต้องการทดลองใช้",
    ],
  },
  "ขายสินค้า": {
    goal: "1.เป้ายอดขาย (บาท)\n2.เป้าปริมาณขาย",
    recordFields: [
      "1.ร้านค้า",
      "2.รายการสินค้า",
      "3.จำนวน",
      "4.ราคาที่ขายได้",
      "5.หมายเหตุ",
    ],
  },
  "เก็บเงิน": {
    goal: "1.เป้ายอดเก็บเงิน (บาท)",
    recordFields: [
      "1. เลขที่ใบแจ้งหนี้",
      "2. จำนวนเงินที่รับชำระ",
      "3. สถานะการชำระ",
      "4. หมายเหตุ",
    ],
  },
  "สำรวจตลาด": {
    goal: "1.จำนวนร้านค้าหรือพื้นที่ที่ต้องสำรวจ",
    recordFields: [
      "1. บริษัทคู่แข่ง",
      "2. สินค้าคู่แข่ง",
      "3. ราคาคู่แข่ง",
      "4. โปรโมชั่นคู่แข่ง",
      "5. ความคิดเห็นของลูกค้า",
    ],
  },
  "แจกสินค้าทดลอง": {
    goal: "1.จำนวนสินค้าที่จะแจก\n2.จำนวนผู้รับ",
    recordFields: [
      "1. รายการสินค้า",
      "2. จำนวนที่แจก",
      "3. ผู้รับสินค้า",
      "4. วัตถุประสงค์ในการแจก",
      "5. วันที่ติดตามผล",
    ],
  },
  "เก็บข้อมูลลูกค้า": {
    goal: "1.จำนวนลูกค้าใหม่ หรือ ลูกค้าที่อัปเดตข้อมูล",
    recordFields: [
      "1. ข้อมูลติดต่อ",
      "2. พื้นที่เพาะปลูก",
      "3.พิกัดแปลง (ถ้ามี)",
      "4. ชนิดพืชหลัก",
      "5. ศักยภาพในการซื้อ",
      "6. หมายเหตุ",
    ],
  },
  "สาธิตการใช้สินค้า": {
    goal: "1.จำนวนผู้เข้าร่วมสาธิต",
    recordFields: [
      "1. ชื่อแปลงสาธิต",
      "2. เจ้าของแปลง",
      "3. รายการสินค้า",
      "4. วิธีการใช้",
      "5.จำนวนผู้เข้าร่วมจริง",
      "6.ความคิดเห็นของผู้เข้าร่วม",
    ],
  },
  "ถ่ายทอดความรู้": {
    goal: "1.จำนวนผู้เข้าร่วม",
    recordFields: [
      "1. หัวข้อที่ถ่ายทอด",
      "2. ผู้ให้คำแนะนำ",
      "3. จำนวนผู้เข้าร่วมจริง",
      "4.ประเด็นคำถามที่ได้รับ",
    ],
  },
  "ติดตามแปลงเพาะปลูก / พืชเป้าหมาย": {
    goal: "1.จำนวนแปลงหรือจำนวนพืชเป้าหมายที่ต้องติดตาม",
    recordFields: [
      "1. พืชเป้าหมาย",
      "2. พันธุ์พืช",
      "3. วันที่ปลูก",
      "4. อายุพืช (วัน)",
      "5. ระยะการเจริญเติบโต",
      "6. พื้นที่เพาะปลูก (ไร่)",
      "7. สภาพพืช (สมบูรณ์/ปานกลาง/ทรุดโทรม)",
      "8. สภาพแปลงเพาะปลูก",
      "9. ผลิตภัณฑ์ที่เคยใช้",
      "10. วันที่ใช้ผลิตภัณฑ์ล่าสุด",
      "11. ผลการใช้ผลิตภัณฑ์",
      "12. ปัญหาที่พบ (ถ้ามี)",
      "13. รูปภาพแปลง",
      "14. วันที่นัดติดตามครั้งถัดไป",
      "15. หมายเหตุ",
    ],
  },
};

const rawMockTripPlans = [
  {
    id: "TP-2026-001",
    activityDate: "2026-07-01",
    responsible: "สมชาย ใจดี",
    approver: "วิชัย มั่นคง",
    jobType: "1.เข้าพบเกษตรกร",
    activityName: "เข้าพบปะพูดคุยแนะนำผลิตภัณฑ์กับกลุ่มเกษตรกร",
    province: "ขอนแก่น",
    district: "เมืองขอนแก่น",
    subdistrict: "ในเมือง",
    locationName: "ตลาดสดเทศบาล 1 ขอนแก่น",
    targetType: "ติดตามลูกค้า",
    budgetType: "งบส่งเสริมการขาย",
    budget: 15000,
    status: "FINISHED",
    actualParticipants: 12,
    actualNewCustomers: 3,
    actualOrders: 5,
    actualSales: 18000,
    targetParticipants: 10,
    targetSales: 15000,
    performanceResult: "บรรลุเป้าหมาย - เกษตรกรสนใจสินค้าทดลองพ่นปุ๋ยรอบใหม่",
    plantType: "ข้าว",
    plotsCount: 2,
    growthStage: "ระยะแตกกอ",
    problemsFound: "พบโรคใบไหม้ระบาดเล็กน้อยในบางแปลง",
    actualBudget: 14500,
    otherExpenses: 2500,
  },
  {
    id: "TP-2026-002",
    activityDate: "2026-07-03",
    responsible: "สมหญิง รักดี",
    approver: "วิชัย มั่นคง",
    jobType: "2.จัดงานขายหน้าร้าน",
    activityName: "จัดงานลดราคาปุ๋ยและของแถมพิเศษหน้าร้านดีลเลอร์",
    province: "เชียงใหม่",
    district: "แม่ริม",
    subdistrict: "แม่สา",
    locationName: "ศูนย์เรียนรู้การเกษตรแม่ริม",
    targetType: "ขายสินค้า",
    budgetType: "งบส่งเสริมการตลาด",
    budget: 45000,
    status: "APPROVED",
    actualParticipants: 45,
    actualNewCustomers: 8,
    actualOrders: 14,
    actualSales: 62000,
    targetParticipants: 40,
    targetSales: 50000,
    performanceResult: "เกินเป้าหมาย - ยอดขายและลูกค้าใหม่หลั่งไหลเข้ามามาก",
    plantType: "ข้าวโพด",
    plotsCount: 1,
    growthStage: "ระยะตั้งท้อง",
    problemsFound: "ขาดน้ำเล็กน้อยเนื่องจากฝนทิ้งช่วง",
    actualBudget: 0,
    otherExpenses: 0,
  },
  {
    id: "TP-2026-003",
    activityDate: "2026-07-05",
    responsible: "พิมพ์ใจ เรียนเก่ง",
    approver: "สมพร ดีเลิศ",
    jobType: "3.งานเลี้ยงลูกค้า",
    activityName: "เลี้ยงอาหารค่ำและเสวนาทางธุรกิจกับคู่ค้ารายใหญ่",
    province: "กรุงเทพฯ",
    district: "ปทุมวัน",
    subdistrict: "ปทุมวัน",
    locationName: "โรงแรมเซ็นทารา แกรนด์",
    targetType: "สร้างความสัมพันธ์",
    budgetType: "งบส่งเสริมการขาย",
    budget: 120000,
    status: "PENDING",
    actualParticipants: 0,
    actualNewCustomers: 0,
    actualOrders: 0,
    actualSales: 0,
    targetParticipants: 30,
    targetSales: 150000,
    performanceResult: "รอดำเนินการ",
    plantType: "พืชไร่",
    plotsCount: 0,
    growthStage: "ยังไม่ปลูก",
    problemsFound: "ไม่มี",
    actualBudget: 0,
    otherExpenses: 0,
  },
  {
    id: "TP-2026-004",
    activityDate: "2026-07-10",
    responsible: "ปรีชา ขยันงาน",
    approver: "สมพร ดีเลิศ",
    jobType: "4.ประชุมเกษตรกร / ดีลเลอร์ / ซับดีลเลอร์",
    activityName: "ประชุมชี้แจงส่วนแบ่งการตลาดและสิทธิประโยชน์",
    province: "นครราชสีมา",
    district: "ปากช่อง",
    subdistrict: "ปากช่อง",
    locationName: "ร้านปากช่องเคมีเกษตร",
    targetType: "ให้คำปรึกษาทางการเกษตร  / ดีลเลอร์ / ซับดีลเลอร์",
    budgetType: "งบส่งเสริมการตลาด",
    budget: 8000,
    status: "REJECTED",
    actualParticipants: 0,
    actualNewCustomers: 0,
    actualOrders: 0,
    actualSales: 0,
    targetParticipants: 15,
    targetSales: 20000,
    performanceResult: "ไม่อนุมัติแผนงาน",
    plantType: "ทุเรียน",
    plotsCount: 0,
    growthStage: "ระยะบำรุงต้น",
    problemsFound: "ไม่มี",
    actualBudget: 0,
    otherExpenses: 0,
  },
  {
    id: "TP-2026-005",
    activityDate: "2026-07-12",
    responsible: "สมชาย ใจดี",
    approver: "วิชัย มั่นคง",
    jobType: "5.ประชุมวิชาการ",
    activityName: "สัมมนาวิชาการปุ๋ยออร์แกนิกและเคมีเกษตรยั่งยืน",
    province: "ขอนแก่น",
    district: "ชุมแพ",
    subdistrict: "ชุมแพ",
    locationName: "ร้านสยามค้าปุ๋ย ชุมแพ",
    targetType: "ถ่ายทอดความรู้",
    budgetType: "งบส่งเสริมการตลาด",
    budget: 5000,
    status: "CANCELLED",
    actualParticipants: 0,
    actualNewCustomers: 0,
    actualOrders: 0,
    actualSales: 0,
    targetParticipants: 50,
    targetSales: 0,
    performanceResult: "ยกเลิกกิจกรรมเนื่องจากพนักงานติดภารกิจอื่น",
    plantType: "ข้าว",
    plotsCount: 0,
    growthStage: "ระยะแตกกอ",
    problemsFound: "ไม่มี",
    actualBudget: 0,
    otherExpenses: 0,
  },
  {
    id: "TP-2026-006",
    activityDate: "2026-07-15",
    responsible: "สมหญิง รักดี",
    approver: "วิชัย มั่นคง",
    jobType: "6.ทำแปลงสาธิต",
    activityName: "ลงมือทำแปลงสาธิตปลูกข้าวโพดทดลองใช้ปุ๋ยสูตรใหม่",
    province: "นครราชสีมา",
    district: "เมืองนครราชสีมา",
    subdistrict: "จอหอ",
    locationName: "ศาลาประชาคมหมู่บ้านโพนพิสัย",
    targetType: "สาธิตการใช้สินค้า",
    budgetType: "งบส่งเสริมการขาย",
    budget: 12000,
    status: "APPROVED",
    actualParticipants: 0,
    actualNewCustomers: 0,
    actualOrders: 0,
    actualSales: 0,
    targetParticipants: 20,
    targetSales: 15000,
    performanceResult: "รอดำเนินการ",
    plantType: "ข้าวโพด",
    plotsCount: 2,
    growthStage: "ระยะงอก",
    problemsFound: "พบวัชพืชหนาแน่นในแปลง",
    actualBudget: 0,
    otherExpenses: 0,
  },
  {
    id: "TP-2026-007",
    activityDate: "2026-07-18",
    responsible: "พิมพ์ใจ เรียนเก่ง",
    approver: "สมพร ดีเลิศ",
    jobType: "7.ฟิลด์เดย์",
    activityName: "จัดวันสาธิตเทคโนโลยีการเพาะปลูกข้าวในพื้นที่แปลงสาธิต",
    province: "เชียงใหม่",
    district: "เมืองเชียงใหม่",
    subdistrict: "ช้างเผือก",
    locationName: "สำนักงานเกษตรจังหวัดเชียงใหม่",
    targetType: "แนะนำสินค้า",
    budgetType: "งบส่งเสริมการตลาด",
    budget: 35000,
    status: "FINISHED",
    actualParticipants: 95,
    actualNewCustomers: 22,
    actualOrders: 18,
    actualSales: 89000,
    targetParticipants: 80,
    targetSales: 75000,
    performanceResult: "เกินเป้าหมาย - เกษตรกรในพื้นที่ให้ความสนใจสูงมาก",
    plantType: "ข้าว",
    plotsCount: 4,
    growthStage: "ระยะเก็บเกี่ยว",
    problemsFound: "พบโรคเมล็ดด่างระบาดในบางมุมของแปลงสาธิต",
    actualBudget: 36000,
    otherExpenses: 4200,
  },
  {
    id: "TP-2026-008",
    activityDate: "2026-07-20",
    responsible: "ปรีชา ขยันงาน",
    approver: "สมพร ดีเลิศ",
    jobType: "1.เข้าพบเกษตรกร",
    activityName: "เดินทางไปเก็บข้อมูลปัญหาการใช้งานปุ๋ยในไร่มันสำปะหลัง",
    province: "กรุงเทพฯ",
    district: "บางรัก",
    subdistrict: "บางรัก",
    locationName: "ลานกิจกรรมสตรีทอาร์ตบางรัก",
    targetType: "รับทราบปัญหา",
    budgetType: "งบส่งเสริมการขาย",
    budget: 85000,
    status: "PENDING",
    actualParticipants: 0,
    actualNewCustomers: 0,
    actualOrders: 0,
    actualSales: 0,
    targetParticipants: 10,
    targetSales: 0,
    performanceResult: "รอดำเนินการ",
    plantType: "มันสำปะหลัง",
    plotsCount: 3,
    growthStage: "ระยะสะสมแป้ง",
    problemsFound: "พบโรคใบด่างมันสำปะหลังระบาด",
    actualBudget: 0,
    otherExpenses: 0,
  },
  {
    id: "TP-2026-009",
    activityDate: "2026-07-22",
    responsible: "สมชาย ใจดี",
    approver: "วิชัย มั่นคง",
    jobType: "2.จัดงานขายหน้าร้าน",
    activityName: "เดินตลาดสำรวจร้านจำหน่ายเคมีเกษตรและคู่แข่ง",
    province: "ขอนแก่น",
    district: "เมืองขอนแก่น",
    subdistrict: "ในเมือง",
    locationName: "ร้านขอนแก่นเจริญการเกษตร",
    targetType: "สำรวจตลาด",
    budgetType: "งบส่งเสริมการตลาด",
    budget: 6000,
    status: "FINISHED",
    actualParticipants: 18,
    actualNewCustomers: 2,
    actualOrders: 4,
    actualSales: 15500,
    targetParticipants: 15,
    targetSales: 10000,
    performanceResult: "บรรลุเป้าหมาย - ได้ข้อมูลคู่แข่งครบถ้วนพร้อมยอดสั่งสั่งสินค้าเพิ่ม",
    plantType: "พืชไร่",
    plotsCount: 1,
    growthStage: "ระยะบำรุงต้น",
    problemsFound: "ไม่มี",
    actualBudget: 5800,
    otherExpenses: 1200,
  },
  {
    id: "TP-2026-010",
    activityDate: "2026-07-25",
    responsible: "สมหญิง รักดี",
    approver: "วิชัย มั่นคง",
    jobType: "3.งานเลี้ยงลูกค้า",
    activityName: "จัดสัมมนาให้ความรู้พร้อมกิจกรรมแจกปุ๋ยตัวอย่างทดลองใช้",
    province: "เชียงใหม่",
    district: "แม่ริม",
    subdistrict: "สะลวง",
    locationName: "วิสาหกิจชุมชนเกษตรอินทรีย์แม่ริม",
    targetType: "แจกสินค้าทดลอง",
    budgetType: "งบส่งเสริมการขาย",
    budget: 50000,
    status: "FINISHED",
    actualParticipants: 62,
    actualNewCustomers: 15,
    actualOrders: 8,
    actualSales: 32000,
    targetParticipants: 50,
    targetSales: 25000,
    performanceResult: "บรรลุเป้าหมาย - สมาชิกวิสาหกิจยินดีกรอกข้อมูลขอรับสินค้าทดลอง",
    plantType: "ส้ม",
    plotsCount: 2,
    growthStage: "ระยะติดผล",
    problemsFound: "พบโรคแคงเกอร์ระบาดในส้มบางต้น",
    actualBudget: 48000,
    otherExpenses: 5500,
  },
  {
    id: "TP-2026-011",
    activityDate: "2026-07-27",
    responsible: "พิมพ์ใจ เรียนเก่ง",
    approver: "สมพร ดีเลิศ",
    jobType: "4.ประชุมเกษตรกร / ดีลเลอร์ / ซับดีลเลอร์",
    activityName: "ประชุมกลุ่มย่อยเกษตรกรตำบลปทุมวันอัปเดตข้อมูลลูกค้า",
    province: "กรุงเทพฯ",
    district: "ปทุมวัน",
    subdistrict: "ปทุมวัน",
    locationName: "ศาลาอเนกประสงค์วัดปทุมวนาราม",
    targetType: "เก็บข้อมูลลูกค้า",
    budgetType: "งบส่งเสริมการขาย",
    budget: 20000,
    status: "APPROVED",
    actualParticipants: 0,
    actualNewCustomers: 0,
    actualOrders: 0,
    actualSales: 0,
    targetParticipants: 25,
    targetSales: 0,
    performanceResult: "รอดำเนินการ",
    plantType: "พืชไร่",
    plotsCount: 0,
    growthStage: "ระยะบำรุงต้น",
    problemsFound: "ไม่มี",
    actualBudget: 0,
    otherExpenses: 0,
  },
  {
    id: "TP-2026-012",
    activityDate: "2026-07-29",
    responsible: "ปรีชา ขยันงาน",
    approver: "สมพร ดีเลิศ",
    jobType: "6.ทำแปลงสาธิต",
    activityName: "ติดตามประเมินผลสภาพต้นและผลผลิต in แปลงทดสอบปุ๋ยทุเรียน",
    province: "นครราชสีมา",
    district: "ปากช่อง",
    subdistrict: "กลางดง",
    locationName: "สวนทุเรียนลุงสมหมาย ปากช่อง",
    targetType: "ติดตามแปลงเพาะปลูก / พืชเป้าหมาย",
    budgetType: "งบส่งเสริมการตลาด",
    budget: 9000,
    status: "APPROVED",
    actualParticipants: 0,
    actualNewCustomers: 0,
    actualOrders: 0,
    actualSales: 0,
    targetParticipants: 5,
    targetSales: 0,
    performanceResult: "รอดำเนินการ",
    plantType: "ทุเรียน",
    plotsCount: 2,
    growthStage: "ระยะติดผล",
    problemsFound: "พบการเข้าทำลายของหนอนเจาะผลทุเรียน",
    actualBudget: 0,
    otherExpenses: 0,
  },
  {
    id: "TP-2026-013",
    activityDate: "2026-08-01",
    responsible: "สมชาย ใจดี",
    approver: "วิชัย มั่นคง",
    jobType: "7.ฟิลด์เดย์",
    activityName: "จัดฟิลด์เดย์แปลงต้นแบบข้าวพันธุ์ดี",
    province: "ขอนแก่น",
    district: "เมืองขอนแก่น",
    subdistrict: "ในเมือง",
    locationName: "ลานอเนกประสงค์บึงแก่นนคร",
    targetType: "แนะนำสินค้า",
    budgetType: "งบส่งเสริมการขาย",
    budget: 150000,
    status: "PENDING",
    actualParticipants: 0,
    actualNewCustomers: 0,
    actualOrders: 0,
    actualSales: 0,
    targetParticipants: 100,
    targetSales: 100000,
    performanceResult: "รอดำเนินการ",
    plantType: "ข้าว",
    plotsCount: 1,
    growthStage: "ระยะสุกแก่",
    problemsFound: "ไม่มี",
    actualBudget: 0,
    otherExpenses: 0,
  },
  {
    id: "TP-2026-014",
    activityDate: "2026-08-05",
    responsible: "สมหญิง รักดี",
    approver: "วิชัย มั่นคง",
    jobType: "1.เข้าพบเกษตรกร",
    activityName: "เข้าเยี่ยมนิคมสหกรณ์การเกษตรและเก็บเช็คค่าปุ๋ยค้างชำระ",
    province: "เชียงใหม่",
    district: "เมืองเชียงใหม่",
    subdistrict: "สุเทพ",
    locationName: "นิคมสหกรณ์แม่แตง สาขาเชียงใหม่",
    targetType: "เก็บเงิน",
    budgetType: "งบส่งเสริมการตลาด",
    budget: 11000,
    status: "APPROVED",
    actualParticipants: 0,
    actualNewCustomers: 0,
    actualOrders: 0,
    actualSales: 0,
    targetParticipants: 8,
    targetSales: 150000,
    performanceResult: "รอดำเนินการ",
    plantType: "ข้าว",
    plotsCount: 0,
    growthStage: "ระยะบำรุงต้น",
    problemsFound: "ไม่มี",
    actualBudget: 0,
    otherExpenses: 0,
  },
  {
    id: "TP-2026-015",
    activityDate: "2026-08-08",
    responsible: "พิมพ์ใจ เรียนเก่ง",
    approver: "สมพร ดีเลิศ",
    jobType: "5.ประชุมวิชาการ",
    activityName: "ประชุมวิชาการปุ๋ยข้าวโพดเขตภาคตะวันออกเฉียงเหนือ",
    province: "นครราชสีมา",
    district: "ปากช่อง",
    subdistrict: "ปากช่อง",
    locationName: "ร้านโคราชปุ๋ยทอง สาขาปากช่อง",
    targetType: "ถ่ายทอดความรู้",
    budgetType: "งบส่งเสริมการขาย",
    budget: 65000,
    status: "APPROVED",
    actualParticipants: 0,
    actualNewCustomers: 0,
    actualOrders: 0,
    actualSales: 0,
    targetParticipants: 60,
    targetSales: 0,
    performanceResult: "รอดำเนินการ",
    plantType: "ข้าวโพด",
    plotsCount: 0,
    growthStage: "ระยะบำรุงต้น",
    problemsFound: "ไม่มี",
    actualBudget: 0,
    otherExpenses: 0,
  },
  {
    id: "TP-2026-016",
    activityDate: "2026-08-10",
    responsible: "ปรีชา ขยันงาน",
    approver: "สมพร ดีเลิศ",
    jobType: "2.จัดงานขายหน้าร้าน",
    activityName: "จัดโปรโมชันนาทีทองลดแจกแถมปุ๋ยเคมีสูตรเด็ด",
    province: "กรุงเทพฯ",
    district: "บางรัก",
    subdistrict: "มหาพฤฒาราม",
    locationName: "ร้านสหกรณ์กรุงเทพ จำกัด",
    targetType: "ขายสินค้า",
    budgetType: "งบส่งเสริมการตลาด",
    budget: 12000,
    status: "PENDING",
    actualParticipants: 0,
    actualNewCustomers: 0,
    actualOrders: 0,
    actualSales: 0,
    targetParticipants: 30,
    targetSales: 40000,
    performanceResult: "รอดำเนินการ",
    plantType: "พืชไร่",
    plotsCount: 0,
    growthStage: "ระยะบำรุงต้น",
    problemsFound: "ไม่มี",
    actualBudget: 0,
    otherExpenses: 0,
  },
  {
    id: "TP-2026-017",
    activityDate: "2026-08-12",
    responsible: "สมชาย ใจดี",
    approver: "วิชัย มั่นคง",
    jobType: "6.ทำแปลงสาธิต",
    activityName: "จัดทำแปลงพ่นปุ๋ยทดสอบประสิทธิภาพพืชเป้าหมาย",
    province: "ขอนแก่น",
    district: "ชุมแพ",
    subdistrict: "หนองไผ่",
    locationName: "แปลงนาสาธิตบ้านหนองไผ่",
    targetType: "ติดตามแปลงเพาะปลูก / พืชเป้าหมาย",
    budgetType: "งบส่งเสริมการขาย",
    budget: 25000,
    status: "FINISHED",
    actualParticipants: 28,
    actualNewCustomers: 5,
    actualOrders: 6,
    actualSales: 21000,
    targetParticipants: 25,
    targetSales: 20000,
    performanceResult: "บรรลุเป้าหมาย - ทดสอบแปลงพ่นปุ๋ยประสบความสำเร็จดีเยี่ยม",
    plantType: "ข้าว",
    plotsCount: 3,
    growthStage: "ระยะออกดอก",
    problemsFound: "พบโรคใบขีดสีส้มเล็กน้อย",
    actualBudget: 24000,
    otherExpenses: 3800,
  },
  {
    id: "TP-2026-018",
    activityDate: "2026-08-15",
    responsible: "สมหญิง รักดี",
    approver: "วิชัย มั่นคง",
    jobType: "1.เข้าพบเกษตรกร",
    activityName: "เข้าพบคู่ค้าปลีกรายย่อยเพื่อรับฟังปัญหาการขนส่งสินค้าชำรุด",
    province: "เชียงใหม่",
    district: "แม่ริม",
    subdistrict: "ริมใต้",
    locationName: "ร้านแม่ริมรุ่งเรืองเกษตร",
    targetType: "รับทราบปัญหา",
    budgetType: "งบส่งเสริมการตลาด",
    budget: 7000,
    status: "REJECTED",
    actualParticipants: 0,
    actualNewCustomers: 0,
    actualOrders: 0,
    actualSales: 0,
    targetParticipants: 5,
    targetSales: 0,
    performanceResult: "ไม่อนุมัติแผนงาน",
    plantType: "พืชไร่",
    plotsCount: 0,
    growthStage: "ระยะบำรุงต้น",
    problemsFound: "ไม่มี",
    actualBudget: 0,
    otherExpenses: 0,
  },
  {
    id: "TP-2026-019",
    activityDate: "2026-08-18",
    responsible: "พิมพ์ใจ เรียนเก่ง",
    approver: "สมพร ดีเลิศ",
    jobType: "3.งานเลี้ยงลูกค้า",
    activityName: "จัดเลี้ยงกระชับความสัมพันธ์ตัวแทนจำหน่ายเขตเหนือ",
    province: "เชียงใหม่",
    district: "เมืองเชียงใหม่",
    subdistrict: "ช้างคลาน",
    locationName: "โรงแรมดิเอ็มเพรส เชียงใหม่",
    targetType: "สร้างความสัมพันธ์",
    budgetType: "งบส่งเสริมการขาย",
    budget: 95000,
    status: "PENDING",
    actualParticipants: 0,
    actualNewCustomers: 0,
    actualOrders: 0,
    actualSales: 0,
    targetParticipants: 40,
    targetSales: 100000,
    performanceResult: "รอดำเนินการ",
    plantType: "พืชไร่",
    plotsCount: 0,
    growthStage: "ระยะบำรุงต้น",
    problemsFound: "ไม่มี",
    actualBudget: 0,
    otherExpenses: 0,
  },
  {
    id: "TP-2026-020",
    activityDate: "2026-08-20",
    responsible: "ปรีชา ขยันงาน",
    approver: "สมพร ดีเลิศ",
    jobType: "1.เข้าพบเกษตรกร",
    activityName: "ลงพื้นที่เจรจาแนะนำสินค้าให้กับเกษตรกรกลุ่มมันสัมปะหลังใหม่",
    province: "นครราชสีมา",
    district: "เมืองนครราชสีมา",
    subdistrict: "ในเมือง",
    locationName: "สหกรณ์การเกษตรเมืองนครราชสีมา",
    targetType: "แนะนำสินค้า",
    budgetType: "งบส่งเสริมการขาย",
    budget: 38000,
    status: "APPROVED",
    actualParticipants: 0,
    actualNewCustomers: 0,
    actualOrders: 0,
    actualSales: 0,
    targetParticipants: 15,
    targetSales: 30000,
    performanceResult: "รอดำเนินการ",
    plantType: "มันสำปะหลัง",
    plotsCount: 1,
    growthStage: "ระยะสะสมแป้ง",
    problemsFound: "ไม่มี",
    actualBudget: 0,
    otherExpenses: 0,
  },
];

export const mockTripPlans: TripPlanMock[] = rawMockTripPlans.map((item) => {
  const config = targetTypeConfigs[item.targetType] || {
    goal: "-",
    recordFields: [],
  };
  return {
    ...item,
    targetGoal: config.goal,
    recordFields: config.recordFields,
  } as TripPlanMock;
});

export interface CustomerMock {
  id: string;
  name: string;
  customerType: string;
  province: string;
  district: string;
  cropType: string;
  responsible: string;
  lastVisitedDate: string;
  status: "ลูกค้าใหม่" | "ลูกค้าปัจจุบัน" | "ลูกค้าไม่เคลื่อนไหว" | "ลูกค้าที่มีปัญหา";
  hasOrder: boolean;
  hasProblem: boolean;
  visitedCount: number;
}

export const mockCustomers: CustomerMock[] = [
  {
    id: "CUST-001",
    name: "ร้านสมบูรณ์การเกษตร",
    customerType: "ตัวแทนจำหน่าย (Dealer)",
    province: "ขอนแก่น",
    district: "เมืองขอนแก่น",
    cropType: "ข้าว",
    responsible: "สมชาย ใจดี",
    lastVisitedDate: "2026-07-01",
    status: "ลูกค้าปัจจุบัน",
    hasOrder: true,
    hasProblem: false,
    visitedCount: 4,
  },
  {
    id: "CUST-002",
    name: "นายทวี พูนผล (ลุงทวี)",
    customerType: "เกษตรกร (Farmer)",
    province: "เชียงใหม่",
    district: "แม่ริม",
    cropType: "ข้าวโพด",
    responsible: "สมหญิง รักดี",
    lastVisitedDate: "2026-07-03",
    status: "ลูกค้าใหม่",
    hasOrder: true,
    hasProblem: false,
    visitedCount: 1,
  },
  {
    id: "CUST-003",
    name: "ร้านเจริญเกษตร ปลวกแดง",
    customerType: "ตัวแทนจำหน่ายย่อย (Subdealer)",
    province: "ขอนแก่น",
    district: "ชุมแพ",
    cropType: "มันสำปะหลัง",
    responsible: "สมชาย ใจดี",
    lastVisitedDate: "2026-07-22",
    status: "ลูกค้าปัจจุบัน",
    hasOrder: true,
    hasProblem: false,
    visitedCount: 3,
  },
  {
    id: "CUST-004",
    name: "นายประหยัด ขยันทำ",
    customerType: "เกษตรกร (Farmer)",
    province: "เชียงใหม่",
    district: "แม่ริม",
    cropType: "ส้ม",
    responsible: "สมหญิง รักดี",
    lastVisitedDate: "2026-07-25",
    status: "ลูกค้าปัจจุบัน",
    hasOrder: true,
    hasProblem: true,
    visitedCount: 5,
  },
  {
    id: "CUST-005",
    name: "ร้านพูนทวีเคมีเกษตร",
    customerType: "ตัวแทนจำหน่าย (Dealer)",
    province: "นครราชสีมา",
    district: "ปากช่อง",
    cropType: "ทุเรียน",
    responsible: "ปรีชา ขยันงาน",
    lastVisitedDate: "2026-07-29",
    status: "ลูกค้าปัจจุบัน",
    hasOrder: false,
    hasProblem: true,
    visitedCount: 2,
  },
  {
    id: "CUST-006",
    name: "นางสมพร ดอนทราย",
    customerType: "นายหน้า (Broker)",
    province: "กรุงเทพฯ",
    district: "บางรัก",
    cropType: "พืชไร่",
    responsible: "ปรีชา ขยันงาน",
    lastVisitedDate: "2026-07-15",
    status: "ลูกค้าปัจจุบัน",
    hasOrder: false,
    hasProblem: false,
    visitedCount: 1,
  },
  {
    id: "CUST-007",
    name: "ร้านมิตรสหายการเกษตร",
    customerType: "ตัวแทนจำหน่ายย่อย (Subdealer)",
    province: "นครราชสีมา",
    district: "เมืองนครราชสีมา",
    cropType: "ข้าวโพด",
    responsible: "สมหญิง รักดี",
    lastVisitedDate: "2026-07-12",
    status: "ลูกค้าปัจจุบัน",
    hasOrder: true,
    hasProblem: false,
    visitedCount: 3,
  },
  {
    id: "CUST-008",
    name: "นายบุญส่ง ส่งเสริม",
    customerType: "เกษตรกร (Farmer)",
    province: "ขอนแก่น",
    district: "ชุมแพ",
    cropType: "ข้าว",
    responsible: "สมชาย ใจดี",
    lastVisitedDate: "2026-08-12",
    status: "ลูกค้าปัจจุบัน",
    hasOrder: true,
    hasProblem: false,
    visitedCount: 6,
  },
  {
    id: "CUST-009",
    name: "ร้านล้านนาเคมีเกษตร",
    customerType: "ตัวแทนจำหน่าย (Dealer)",
    province: "เชียงใหม่",
    district: "เมืองเชียงใหม่",
    cropType: "พืชไร่",
    responsible: "พิมพ์ใจ เรียนเก่ง",
    lastVisitedDate: "2026-07-18",
    status: "ลูกค้าที่มีปัญหา",
    hasOrder: false,
    hasProblem: true,
    visitedCount: 2,
  },
  {
    id: "CUST-010",
    name: "นายสมาน รักดิน",
    customerType: "เกษตรกร (Farmer)",
    province: "นครราชสีมา",
    district: "ปากช่อง",
    cropType: "มันสำปะหลัง",
    responsible: "ปรีชา ขยันงาน",
    lastVisitedDate: "2026-08-20",
    status: "ลูกค้าใหม่",
    hasOrder: false,
    hasProblem: false,
    visitedCount: 1,
  },
  {
    id: "CUST-011",
    name: "ร้านปากช่องรุ่งเรือง",
    customerType: "ตัวแทนจำหน่ายย่อย (Subdealer)",
    province: "นครราชสีมา",
    district: "ปากช่อง",
    cropType: "ทุเรียน",
    responsible: "ปรีชา ขยันงาน",
    lastVisitedDate: "2026-07-10",
    status: "ลูกค้าไม่เคลื่อนไหว",
    hasOrder: false,
    hasProblem: false,
    visitedCount: 0,
  },
  {
    id: "CUST-012",
    name: "นางประดับ แก้ววิจิตร",
    customerType: "เกษตรกร (Farmer)",
    province: "ขอนแก่น",
    district: "เมืองขอนแก่น",
    cropType: "ข้าว",
    responsible: "สมชาย ใจดี",
    lastVisitedDate: "2026-07-01",
    status: "ลูกค้าปัจจุบัน",
    hasOrder: true,
    hasProblem: false,
    visitedCount: 4,
  },
  {
    id: "CUST-013",
    name: "ร้านเจริญพันธุ์ เชียงใหม่",
    customerType: "ตัวแทนจำหน่าย (Dealer)",
    province: "เชียงใหม่",
    district: "เมืองเชียงใหม่",
    cropType: "ส้ม",
    responsible: "พิมพ์ใจ เรียนเก่ง",
    lastVisitedDate: "2026-08-19",
    status: "ลูกค้าปัจจุบัน",
    hasOrder: true,
    hasProblem: false,
    visitedCount: 3,
  },
  {
    id: "CUST-014",
    name: "นางประดับ ช่วยเหลือ",
    customerType: "นายหน้า (Broker)",
    province: "กรุงเทพฯ",
    district: "บางรัก",
    cropType: "พืชไร่",
    responsible: "พิมพ์ใจ เรียนเก่ง",
    lastVisitedDate: "2026-07-05",
    status: "ลูกค้าไม่เคลื่อนไหว",
    hasOrder: false,
    hasProblem: false,
    visitedCount: 0,
  },
  {
    id: "CUST-015",
    name: "ร้านนครราชเคมีเกษตร",
    customerType: "ตัวแทนจำหน่าย (Dealer)",
    province: "นครราชสีมา",
    district: "เมืองนครราชสีมา",
    cropType: "มันสำปะหลัง",
    responsible: "สมหญิง รักดี",
    lastVisitedDate: "2026-08-20",
    status: "ลูกค้าใหม่",
    hasOrder: false,
    hasProblem: false,
    visitedCount: 1,
  },
  {
    id: "CUST-016",
    name: "นายทองดี มีนา",
    customerType: "เกษตรกร (Farmer)",
    province: "ขอนแก่น",
    district: "เมืองขอนแก่น",
    cropType: "ข้าว",
    responsible: "สมชาย ใจดี",
    lastVisitedDate: "2026-08-01",
    status: "ลูกค้าใหม่",
    hasOrder: false,
    hasProblem: false,
    visitedCount: 1,
  },
  {
    id: "CUST-017",
    name: "ร้านสันทรายรุ่งเรือง",
    customerType: "ตัวแทนจำหน่ายย่อย (Subdealer)",
    province: "เชียงใหม่",
    district: "แม่ริม",
    cropType: "ข้าวโพด",
    responsible: "สมหญิง รักดี",
    lastVisitedDate: "2026-08-15",
    status: "ลูกค้าปัจจุบัน",
    hasOrder: true,
    hasProblem: false,
    visitedCount: 2,
  },
  {
    id: "CUST-018",
    name: "นายมั่นคง แน่วแน่",
    customerType: "เกษตรกร (Farmer)",
    province: "นครราชสีมา",
    district: "ปากช่อง",
    cropType: "ทุเรียน",
    responsible: "ปรีชา ขยันงาน",
    lastVisitedDate: "2026-07-29",
    status: "ลูกค้าปัจจุบัน",
    hasOrder: true,
    hasProblem: false,
    visitedCount: 4,
  },
  {
    id: "CUST-019",
    name: "ร้านสหกรณ์ปากช่อง จำกัด",
    customerType: "ตัวแทนจำหน่าย (Dealer)",
    province: "นครราชสีมา",
    district: "ปากช่อง",
    cropType: "ข้าวโพด",
    responsible: "พิมพ์ใจ เรียนเก่ง",
    lastVisitedDate: "2026-08-08",
    status: "ลูกค้าปัจจุบัน",
    hasOrder: true,
    hasProblem: false,
    visitedCount: 2,
  },
  {
    id: "CUST-020",
    name: "นายอุดม อุดมทรัพย์",
    customerType: "เกษตรกร (Farmer)",
    province: "เชียงใหม่",
    district: "แม่ริม",
    cropType: "ข้าวโพด",
    responsible: "สมหญิง รักดี",
    lastVisitedDate: "2026-08-18",
    status: "ลูกค้าที่มีปัญหา",
    hasOrder: false,
    hasProblem: true,
    visitedCount: 1,
  },
];
