export interface TripPlanMock {
  id: string;
  activityDate: string;
  responsible: string;
  approver: string;
  jobType: string;
  activityName: string;
  province: string;
  district: string;
  subdistrict: string;
  locationName: string;
  targetType: string;
  targetGoal: string;
  recordFields: string[];
  budgetType: string;
  budget: number;
  status: "PENDING" | "APPROVED" | "REJECTED" | "CANCELLED" | "FINISHED";
}

export const targetTypeConfigs: Record<
  string,
  { goal: string; recordFields: string[] }
> = {
  "ติดตามลูกค้า": {
    goal: "1.จำนวนลูกค้าที่ต้องติดตาม (ราย)",
    recordFields: [
      "1. ลูกค้าที่เข้าพบ",
      "2. สินค้าที่เคยซื้อ",
      "3. ผลการติดตาม",
      "4. ปัญหาที่พบ",
      "5. สิ่งที่ต้องดำเนินการต่อ",
      "6. วันที่นัดหมายครั้งถัดไป",
    ],
  },
  "สร้างความสัมพันธ์": {
    goal: "1.จำนวนลูกค้าที่ต้องเข้าพบ (ราย)",
    recordFields: [
      "1. ลูกค้าที่เข้าพบ",
      "2. ประเด็นที่พูดคุย",
      "3. ความคิดเห็นของลูกค้า",
      "4. ความพึงพอใจของลูกค้า",
      "5. โอกาสทางธุรกิจที่พบ",
    ],
  },
  "รับทราบปัญหา": {
    goal: "1.จำนวนเคสที่ต้องติดตาม",
    recordFields: [
      "1. ลูกค้าที่แจ้งปัญหา",
      "2. ประเภทปัญหา",
      "   - สินค้าชำรุด",
      "   - ขอเคลมสินค้า",
      "   - การใช้งานสินค้า",
      "   - โรคและแมลง",
      "   - ส่งสินค้าไม่ครบ",
      "   - อื่น ๆ (ระบุ)",
      "3. พื้นที่เพาะปลูก",
      "4. รายละเอียดปัญหา",
      "5. รูปภาพประกอบ",
      "6. แนวทางแก้ไขเบื้องต้น",
    ],
  },
  "ให้คำปรึกษาทางการเกษตร  / ดีลเลอร์ / ซับดีลเลอร์": {
    goal: "1.จำนวนคนที่คาดว่าจะให้คำปรึกษา",
    recordFields: [
      "1. หัวข้อที่ให้คำแนะนำ",
      "2. ปัญหาของลูกค้า",
      "3. คำแนะนำที่ให้",
    ],
  },
  "แนะนำสินค้า": {
    goal: "1.จำนวนลูกค้าที่คาดว่าจะสนใจ",
    recordFields: [
      "1. สินค้าที่แนะนำ",
      "2. เหตุผลที่แนะนำ",
      "3. ความสนใจของลูกค้า",
      "4. ความต้องการทดลองใช้",
    ],
  },
  "ขายสินค้า": {
    goal: "1.เป้ายอดขาย (บาท)\n2.เป้าปริมาณขาย",
    recordFields: [
      "1.ร้านค้า",
      "2.รายการสินค้า",
      "3.จำนวน",
      "4.ราคาที่ขายได้",
      "5.หมายเหตุ",
    ],
  },
  "เก็บเงิน": {
    goal: "1.เป้ายอดเก็บเงิน (บาท)",
    recordFields: [
      "1. เลขที่ใบแจ้งหนี้",
      "2. จำนวนเงินที่รับชำระ",
      "3. สถานะการชำระ",
      "4. หมายเหตุ",
    ],
  },
  "สำรวจตลาด": {
    goal: "1.จำนวนร้านค้าหรือพื้นที่ที่ต้องสำรวจ",
    recordFields: [
      "1. บริษัทคู่แข่ง",
      "2. สินค้าคู่แข่ง",
      "3. ราคาคู่แข่ง",
      "4. โปรโมชั่นคู่แข่ง",
      "5. ความคิดเห็นของลูกค้า",
    ],
  },
  "แจกสินค้าทดลอง": {
    goal: "1.จำนวนสินค้าที่จะแจก\n2.จำนวนผู้รับ",
    recordFields: [
      "1. รายการสินค้า",
      "2. จำนวนที่แจก",
      "3. ผู้รับสินค้า",
      "4. วัตถุประสงค์ในการแจก",
      "5. วันที่ติดตามผล",
    ],
  },
  "เก็บข้อมูลลูกค้า": {
    goal: "1.จำนวนลูกค้าใหม่ หรือ ลูกค้าที่อัปเดตข้อมูล",
    recordFields: [
      "1. ข้อมูลติดต่อ",
      "2. พื้นที่เพาะปลูก",
      "3.พิกัดแปลง (ถ้ามี)",
      "4. ชนิดพืชหลัก",
      "5. ศักยภาพในการซื้อ",
      "6. หมายเหตุ",
    ],
  },
  "สาธิตการใช้สินค้า": {
    goal: "1.จำนวนผู้เข้าร่วมสาธิต",
    recordFields: [
      "1. ชื่อแปลงสาธิต",
      "2. เจ้าของแปลง",
      "3. รายการสินค้า",
      "4. วิธีการใช้",
      "5.จำนวนผู้เข้าร่วมจริง",
      "6.ความคิดเห็นของผู้เข้าร่วม",
    ],
  },
  "ถ่ายทอดความรู้": {
    goal: "1.จำนวนผู้เข้าร่วม",
    recordFields: [
      "1. หัวข้อที่ถ่ายทอด",
      "2. ผู้ให้คำแนะนำ",
      "3. จำนวนผู้เข้าร่วมจริง",
      "4.ประเด็นคำถามที่ได้รับ",
    ],
  },
  "ติดตามแปลงเพาะปลูก / พืชเป้าหมาย": {
    goal: "1.จำนวนแปลงหรือจำนวนพืชเป้าหมายที่ต้องติดตาม",
    recordFields: [
      "1. พืชเป้าหมาย",
      "2. พันธุ์พืช",
      "3. วันที่ปลูก",
      "4. อายุพืช (วัน)",
      "5. ระยะการเจริญเติบโต",
      "6. พื้นที่เพาะปลูก (ไร่)",
      "7. สภาพพืช (สมบูรณ์/ปานกลาง/ทรุดโทรม)",
      "8. สภาพแปลงเพาะปลูก",
      "9. ผลิตภัณฑ์ที่เคยใช้",
      "10. วันที่ใช้ผลิตภัณฑ์ล่าสุด",
      "11. ผลการใช้ผลิตภัณฑ์",
      "12. ปัญหาที่พบ (ถ้ามี)",
      "13. รูปภาพแปลง",
      "14. วันที่นัดติดตามครั้งถัดไป",
      "15. หมายเหตุ",
    ],
  },
};

const rawMockTripPlans = [
  {
    id: "TP-2026-001",
    activityDate: "2026-07-01",
    responsible: "สมชาย ใจดี",
    approver: "วิชัย มั่นคง",
    jobType: "1.เข้าพบเกษตรกร",
    activityName: "เข้าพบปะพูดคุยแนะนำผลิตภัณฑ์กับกลุ่มเกษตรกร",
    province: "ขอนแก่น",
    district: "เมืองขอนแก่น",
    subdistrict: "ในเมือง",
    locationName: "ตลาดสดเทศบาล 1 ขอนแก่น",
    targetType: "ติดตามลูกค้า",
    budgetType: "งบส่งเสริมการขาย",
    budget: 15000,
    status: "FINISHED",
  },
  {
    id: "TP-2026-002",
    activityDate: "2026-07-03",
    responsible: "สมหญิง รักดี",
    approver: "วิชัย มั่นคง",
    jobType: "2.จัดงานขายหน้าร้าน",
    activityName: "จัดงานลดราคาปุ๋ยและของแถมพิเศษหน้าร้านดีลเลอร์",
    province: "เชียงใหม่",
    district: "แม่ริม",
    subdistrict: "แม่สา",
    locationName: "ศูนย์เรียนรู้การเกษตรแม่ริม",
    targetType: "ขายสินค้า",
    budgetType: "งบส่งเสริมการตลาด",
    budget: 45000,
    status: "APPROVED",
  },
  {
    id: "TP-2026-003",
    activityDate: "2026-07-05",
    responsible: "พิมพ์ใจ เรียนเก่ง",
    approver: "สมพร ดีเลิศ",
    jobType: "3.งานเลี้ยงลูกค้า",
    activityName: "เลี้ยงอาหารค่ำและเสวนาทางธุรกิจกับคู่ค้ารายใหญ่",
    province: "กรุงเทพฯ",
    district: "ปทุมวัน",
    subdistrict: "ปทุมวัน",
    locationName: "โรงแรมเซ็นทารา แกรนด์",
    targetType: "สร้างความสัมพันธ์",
    budgetType: "งบส่งเสริมการขาย",
    budget: 120000,
    status: "PENDING",
  },
  {
    id: "TP-2026-004",
    activityDate: "2026-07-10",
    responsible: "ปรีชา ขยันงาน",
    approver: "สมพร ดีเลิศ",
    jobType: "4.ประชุมเกษตรกร / ดีลเลอร์ / ซับดีลเลอร์",
    activityName: "ประชุมชี้แจงส่วนแบ่งการตลาดและสิทธิประโยชน์",
    province: "นครราชสีมา",
    district: "ปากช่อง",
    subdistrict: "ปากช่อง",
    locationName: "ร้านปากช่องเคมีเกษตร",
    targetType: "ให้คำปรึกษาทางการเกษตร  / ดีลเลอร์ / ซับดีลเลอร์",
    budgetType: "งบส่งเสริมการตลาด",
    budget: 8000,
    status: "REJECTED",
  },
  {
    id: "TP-2026-005",
    activityDate: "2026-07-12",
    responsible: "สมชาย ใจดี",
    approver: "วิชัย มั่นคง",
    jobType: "5.ประชุมวิชาการ",
    activityName: "สัมมนาวิชาการปุ๋ยออร์แกนิกและเคมีเกษตรยั่งยืน",
    province: "ขอนแก่น",
    district: "ชุมแพ",
    subdistrict: "ชุมแพ",
    locationName: "ร้านสยามค้าปุ๋ย ชุมแพ",
    targetType: "ถ่ายทอดความรู้",
    budgetType: "งบส่งเสริมการตลาด",
    budget: 5000,
    status: "CANCELLED",
  },
  {
    id: "TP-2026-006",
    activityDate: "2026-07-15",
    responsible: "สมหญิง รักดี",
    approver: "วิชัย มั่นคง",
    jobType: "6.ทำแปลงสาธิต",
    activityName: "ลงมือทำแปลงสาธิตปลูกข้าวโพดทดลองใช้ปุ๋ยสูตรใหม่",
    province: "นครราชสีมา",
    district: "เมืองนครราชสีมา",
    subdistrict: "จอหอ",
    locationName: "ศาลาประชาคมหมู่บ้านโพนพิสัย",
    targetType: "สาธิตการใช้สินค้า",
    budgetType: "งบส่งเสริมการขาย",
    budget: 12000,
    status: "APPROVED",
  },
  {
    id: "TP-2026-007",
    activityDate: "2026-07-18",
    responsible: "พิมพ์ใจ เรียนเก่ง",
    approver: "สมพร ดีเลิศ",
    jobType: "7.ฟิลด์เดย์",
    activityName: "จัดวันสาธิตเทคโนโลยีการเพาะปลูกข้าวในพื้นที่แปลงสาธิต",
    province: "เชียงใหม่",
    district: "เมืองเชียงใหม่",
    subdistrict: "ช้างเผือก",
    locationName: "สำนักงานเกษตรจังหวัดเชียงใหม่",
    targetType: "แนะนำสินค้า",
    budgetType: "งบส่งเสริมการตลาด",
    budget: 35000,
    status: "FINISHED",
  },
  {
    id: "TP-2026-008",
    activityDate: "2026-07-20",
    responsible: "ปรีชา ขยันงาน",
    approver: "สมพร ดีเลิศ",
    jobType: "1.เข้าพบเกษตรกร",
    activityName: "เดินทางไปเก็บข้อมูลปัญหาการใช้งานปุ๋ยในไร่มันสำปะหลัง",
    province: "กรุงเทพฯ",
    district: "บางรัก",
    subdistrict: "บางรัก",
    locationName: "ลานกิจกรรมสตรีทอาร์ตบางรัก",
    targetType: "รับทราบปัญหา",
    budgetType: "งบส่งเสริมการขาย",
    budget: 85000,
    status: "PENDING",
  },
  {
    id: "TP-2026-009",
    activityDate: "2026-07-22",
    responsible: "สมชาย ใจดี",
    approver: "วิชัย มั่นคง",
    jobType: "2.จัดงานขายหน้าร้าน",
    activityName: "เดินตลาดสำรวจร้านจำหน่ายเคมีเกษตรและคู่แข่ง",
    province: "ขอนแก่น",
    district: "เมืองขอนแก่น",
    subdistrict: "ในเมือง",
    locationName: "ร้านขอนแก่นเจริญการเกษตร",
    targetType: "สำรวจตลาด",
    budgetType: "งบส่งเสริมการตลาด",
    budget: 6000,
    status: "FINISHED",
  },
  {
    id: "TP-2026-010",
    activityDate: "2026-07-25",
    responsible: "สมหญิง รักดี",
    approver: "วิชัย มั่นคง",
    jobType: "3.งานเลี้ยงลูกค้า",
    activityName: "จัดสัมมนาให้ความรู้พร้อมกิจกรรมแจกปุ๋ยตัวอย่างทดลองใช้",
    province: "เชียงใหม่",
    district: "แม่ริม",
    subdistrict: "สะลวง",
    locationName: "วิสาหกิจชุมชนเกษตรอินทรีย์แม่ริม",
    targetType: "แจกสินค้าทดลอง",
    budgetType: "งบส่งเสริมการขาย",
    budget: 50000,
    status: "FINISHED",
  },
  {
    id: "TP-2026-011",
    activityDate: "2026-07-27",
    responsible: "พิมพ์ใจ เรียนเก่ง",
    approver: "สมพร ดีเลิศ",
    jobType: "4.ประชุมเกษตรกร / ดีลเลอร์ / ซับดีลเลอร์",
    activityName: "ประชุมกลุ่มย่อยเกษตรกรตำบลปทุมวันอัปเดตข้อมูลลูกค้า",
    province: "กรุงเทพฯ",
    district: "ปทุมวัน",
    subdistrict: "ปทุมวัน",
    locationName: "ศาลาอเนกประสงค์วัดปทุมวนาราม",
    targetType: "เก็บข้อมูลลูกค้า",
    budgetType: "งบส่งเสริมการขาย",
    budget: 20000,
    status: "APPROVED",
  },
  {
    id: "TP-2026-012",
    activityDate: "2026-07-29",
    responsible: "ปรีชา ขยันงาน",
    approver: "สมพร ดีเลิศ",
    jobType: "6.ทำแปลงสาธิต",
    activityName: "ติดตามประเมินผลสภาพต้นและผลผลิตในแปลงทดสอบปุ๋ยทุเรียน",
    province: "นครราชสีมา",
    district: "ปากช่อง",
    subdistrict: "กลางดง",
    locationName: "สวนทุเรียนลุงสมหมาย ปากช่อง",
    targetType: "ติดตามแปลงเพาะปลูก / พืชเป้าหมาย",
    budgetType: "งบส่งเสริมการตลาด",
    budget: 9000,
    status: "APPROVED",
  },
  {
    id: "TP-2026-013",
    activityDate: "2026-08-01",
    responsible: "สมชาย ใจดี",
    approver: "วิชัย มั่นคง",
    jobType: "7.ฟิลด์เดย์",
    activityName: "จัดฟิลด์เดย์แปลงต้นแบบข้าวพันธุ์ดี",
    province: "ขอนแก่น",
    district: "เมืองขอนแก่น",
    subdistrict: "ในเมือง",
    locationName: "ลานอเนกประสงค์บึงแก่นนคร",
    targetType: "แนะนำสินค้า",
    budgetType: "งบส่งเสริมการขาย",
    budget: 150000,
    status: "PENDING",
  },
  {
    id: "TP-2026-014",
    activityDate: "2026-08-05",
    responsible: "สมหญิง รักดี",
    approver: "วิชัย มั่นคง",
    jobType: "1.เข้าพบเกษตรกร",
    activityName: "เข้าเยี่ยมนิคมสหกรณ์การเกษตรและเก็บเช็คค่าปุ๋ยค้างชำระ",
    province: "เชียงใหม่",
    district: "เมืองเชียงใหม่",
    subdistrict: "สุเทพ",
    locationName: "นิคมสหกรณ์แม่แตง สาขาเชียงใหม่",
    targetType: "เก็บเงิน",
    budgetType: "งบส่งเสริมการตลาด",
    budget: 11000,
    status: "APPROVED",
  },
  {
    id: "TP-2026-015",
    activityDate: "2026-08-08",
    responsible: "พิมพ์ใจ เรียนเก่ง",
    approver: "สมพร ดีเลิศ",
    jobType: "5.ประชุมวิชาการ",
    activityName: "ประชุมวิชาการปุ๋ยข้าวโพดเขตภาคตะวันออกเฉียงเหนือ",
    province: "นครราชสีมา",
    district: "ปากช่อง",
    subdistrict: "ปากช่อง",
    locationName: "ร้านโคราชปุ๋ยทอง สาขาปากช่อง",
    targetType: "ถ่ายทอดความรู้",
    budgetType: "งบส่งเสริมการขาย",
    budget: 65000,
    status: "APPROVED",
  },
  {
    id: "TP-2026-016",
    activityDate: "2026-08-10",
    responsible: "ปรีชา ขยันงาน",
    approver: "สมพร ดีเลิศ",
    jobType: "2.จัดงานขายหน้าร้าน",
    activityName: "จัดโปรโมชันนาทีทองลดแจกแถมปุ๋ยเคมีสูตรเด็ด",
    province: "กรุงเทพฯ",
    district: "บางรัก",
    subdistrict: "มหาพฤฒาราม",
    locationName: "ร้านสหกรณ์กรุงเทพ จำกัด",
    targetType: "ขายสินค้า",
    budgetType: "งบส่งเสริมการตลาด",
    budget: 12000,
    status: "PENDING",
  },
  {
    id: "TP-2026-017",
    activityDate: "2026-08-12",
    responsible: "สมชาย ใจดี",
    approver: "วิชัย มั่นคง",
    jobType: "6.ทำแปลงสาธิต",
    activityName: "จัดทำแปลงพ่นปุ๋ยทดสอบประสิทธิภาพพืชเป้าหมาย",
    province: "ขอนแก่น",
    district: "ชุมแพ",
    subdistrict: "หนองไผ่",
    locationName: "แปลงนาสาธิตบ้านหนองไผ่",
    targetType: "ติดตามแปลงเพาะปลูก / พืชเป้าหมาย",
    budgetType: "งบส่งเสริมการขาย",
    budget: 25000,
    status: "FINISHED",
  },
  {
    id: "TP-2026-018",
    activityDate: "2026-08-15",
    responsible: "สมหญิง รักดี",
    approver: "วิชัย มั่นคง",
    jobType: "1.เข้าพบเกษตรกร",
    activityName: "เข้าพบคู่ค้าปลีกรายย่อยเพื่อรับฟังปัญหาการขนส่งสินค้าชำรุด",
    province: "เชียงใหม่",
    district: "แม่ริม",
    subdistrict: "ริมใต้",
    locationName: "ร้านแม่ริมรุ่งเรืองเกษตร",
    targetType: "รับทราบปัญหา",
    budgetType: "งบส่งเสริมการตลาด",
    budget: 7000,
    status: "REJECTED",
  },
  {
    id: "TP-2026-019",
    activityDate: "2026-08-18",
    responsible: "พิมพ์ใจ เรียนเก่ง",
    approver: "สมพร ดีเลิศ",
    jobType: "3.งานเลี้ยงลูกค้า",
    activityName: "จัดเลี้ยงกระชับความสัมพันธ์ตัวแทนจำหน่ายเขตเหนือ",
    province: "เชียงใหม่",
    district: "เมืองเชียงใหม่",
    subdistrict: "ช้างคลาน",
    locationName: "โรงแรมดิเอ็มเพรส เชียงใหม่",
    targetType: "สร้างความสัมพันธ์",
    budgetType: "งบส่งเสริมการขาย",
    budget: 95000,
    status: "PENDING",
  },
  {
    id: "TP-2026-020",
    activityDate: "2026-08-20",
    responsible: "ปรีชา ขยันงาน",
    approver: "สมพร ดีเลิศ",
    jobType: "1.เข้าพบเกษตรกร",
    activityName: "ลงพื้นที่เจรจาแนะนำสินค้าให้กับเกษตรกรกลุ่มมันสัมปะหลังใหม่",
    province: "นครราชสีมา",
    district: "เมืองนครราชสีมา",
    subdistrict: "ในเมือง",
    locationName: "สหกรณ์การเกษตรเมืองนครราชสีมา",
    targetType: "แนะนำสินค้า",
    budgetType: "งบส่งเสริมการขาย",
    budget: 38000,
    status: "APPROVED",
  },
];

export const mockTripPlans: TripPlanMock[] = rawMockTripPlans.map((item) => {
  const config = targetTypeConfigs[item.targetType] || {
    goal: "-",
    recordFields: [],
  };
  return {
    ...item,
    targetGoal: config.goal,
    recordFields: config.recordFields,
  } as TripPlanMock;
});
